image: docker:latest

services:
  - docker:dind

# Docker Cloud Variables
# Note: to use the Gitlab CI Registry, delete the variables from the CI settings.
# `echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin`
before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
  - apk add --no-cache bash

# For basic CI
build-ci:
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE
  script:
    - docker build -f Dockerfile -t $CI_REGISTRY_IMAGE/base .
    - docker login docker.io
    - docker push $IMAGE_TAG/base
  only:
    - master

# For LEMP
build-all-versions:
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE
  script:
    - docker login docker.io
    - ./build-ci.sh
  only:
    - master
