image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

after_script:
- docker login -u $DOCKER_CLOUD_USER -p $DOCKER_CLOUD_PASSWORD
- docker push beyondlimits99/php:php7.2-nginx

# Master
build-master:
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/php
  script:
    - echo "The image tag is $IMAGE_TAG"
    - docker build --pull -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - master

build-tag:
  stage: build
  only:
    - tags
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/php:$CI_COMMIT_TAG
  script:
    - echo "The image tag is $IMAGE_TAG"
    - docker build --pull -t $IMAGE_TAG .
    - docker push $IMAGE_TAG