image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

build-master:
  stage: build
  script:
    - docker build --pull -t "$CI_PROJECT_NAME" .
    - docker images
  only:
    - master

deploy-gitlab:
  stage: deploy
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - docker push "$CI_PROJECT_NAME"

deploy-docker:
  stage: deploy
  script:
    - echo "DOCKER_CLOUD_PASSWORD" | docker login -u "DOCKER_CLOUD_USER" --password-stdin
    - docker push "$CI_PROJECT_NAME"