image: docker:latest

services:
  - docker:dind

# Docker Cloud Variables
# Note: to use the Gitlab CI Registry, delete the variables from the CI settings.
# `echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin`
before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
  - apk add --no-cache bash

# Master
build-current-verion:
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE
  script:
    - echo "The image tag is $IMAGE_TAG"
    - docker build --pull -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - master

# Build All, minus current version
build-all-versions:
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE
  script:
    - ./build.sh
  only:
    - master

# Tags
build-tag:
  stage: build
  only:
    - tags
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/php:$CI_COMMIT_TAG
  script:
    - echo "The image tag is $IMAGE_TAG"
    - docker build --pull -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
