version: '3'
services:
  web:
    build: .
    environment:
      XDEBUG_HOST: 192.168.0.6
      XDEBUG_IDEKEY: PHPSTORM
      XDEBUG_REMOTE_PORT: 9000
    volumes:
      - ./app:/var/www/html
    ports:
      - 7000:80
    tty: true
volumes:
  dbdata: