version: '3'
services:
  web:
    image: robmellett/php:7.2
    hostname: docker
    dns: 8.8.8.8
    env_file:
      - .docker.env
    environment:
      CONTAINER_ROLE: app # [app, queue, scheduler]
      APP_ENV: local # [local, staging, production]
    volumes:
      - ./app:/var/www/html
    ports:
      - 7000:80 # Web
      - 7090:9100 # Prometheus, node_exporter
    tty: true
volumes:
  dbdata:
