version: '3'
services:
  docker-web:
    image: robmellett/lemp:7.3
    hostname: docker-web
    container_name: docker-web
    dns: 8.8.8.8
    env_file:
      - .docker.env
    environment:
      CONTAINER_ROLE: app # [app, queue, scheduler]
      APP_ENV: local # [local, staging, production]
    volumes:
      - ./app:/var/www/html
    networks:
      - acme
    ports:
      - 7000:80 # Web
      - 443:443 # Https
      - 7090:9100 # Prometheus, node_exporter
    tty: true

  docker-redis:
    image: redis:latest
    hostname: docker-redis
    container_name: docker-redis
    ports:
      - 6379:6379
    networks:
      - acme

  docker-mysql:
    image: mysql:latest
    hostname: docker-mysql
    container_name: docker-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - acme
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root

volumes:
  db-data:

networks:
  acme:
    driver: bridge
