version: '3'
services:
  web:
    image: robmellett/lemp:7.3
    hostname: docker-web
    container_name: docker-web
    dns: 8.8.8.8
    env_file:
      - .docker.env
    environment:
      CONTAINER_ROLE: app # [app, queue, scheduler]
      APP_ENV: local # [local, staging, production]
    volumes:
      - ./app:/var/www/html
    networks:
      acme:
         ipv4_address: 172.16.0.2
    ports:
      - 7000:80 # Web
      - 443:443 # Https
      - 7090:9100 # Prometheus, node_exporter
    tty: true

  docker-mysql:
    image: mysql:latest
    hostname: docker-mysql
    container_name: docker-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      acme:
        ipv4_address: 172.16.0.5
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root

volumes:
  dbdata:

networks:
  acme:
    ipam:
      config:
        - subnet: "172.16.0.0/16"
