version: '3'
services:
  web:
    image: robmellett/lemp:7.2
    hostname: docker-web
    container_name: docker-web
    dns: 8.8.8.8
    env_file:
      - .docker.env
    environment:
      CONTAINER_ROLE: app # [app, queue, scheduler]
      APP_ENV: local # [local, staging, production]
    volumes:
      - ./app:/var/www/html
    networks:
      acme:
         ipv4_address: 172.16.238.10 # Use this for databases
    ports:
      - 7000:80 # Web
      - 7090:9100 # Prometheus, node_exporter
    tty: true

volumes:
  dbdata:

networks:
  acme:
    ipam:
      config:
        - subnet: "172.16.238.0/24"
