version: '3'
services:
  web:
    build: .
    env_file:
      - .docker.env
    environment:
      CONTAINER_ROLE: app # [app, queue, scheduler]
      APP_ENV: local # [local, staging, production]
    volumes:
      - ./app:/var/www/html
    ports:
      - 7000:80
    tty: true
volumes:
  dbdata: